language: ruby

rvm:
  - 2.2.3
install:
  - bundle install --retry=3
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  flowdock:
    secure: LuhbnBcKmSr1FBtVV2BGxi2HE5mdD0hc7km0k+0o8S2Sh1H9VwfOmSN7/CPXbeXJM+rdhYDOSmr6Smih+jhNy4tvjxltSawTchriJQbBWbIuwWZav6Py8yJoyMBR9jTbFCV3ZMSRT0z/s2IA9/Uh6/txx6f3FHmn0qXRF4TX98Fe45w/CZiQY7GPzb/rYEB4zmuHuTJvL5iEuV2Mq2zz01sHzBhmSmdCy2tIxAZ+XHjJ0MYasLAhBNAJ1o5GsRLuHCNAoiztf1bsGnoqmCsIl+w4fwpQr46lriLpP5IOM8fynmu/lhI3Wz01MMwM9OlKyV9Syt7iz//qk9QSAqqvm+4Y5Ixlf6TxnwhEMvrVv6qHaOyHW1yrrNcRv7AiuXHXAwix5WaiZmEaJAeOLBBTpSEzi2kVRr5piF9dU/xbFOupMrgyn8QOhsPbwoVwR0YSK9OrlTxPwLCzhSJx1O2M/0WbxY/fOxopSAl3j/MZ+5tGVQwzzeuHEev3iSKIODwXGloBmZ+AnEuZee/6qyPzoW62x1FKhEQhyqDTcUqeuf1kST83mGAEQRtUb+/8npYVdJ6qfB3Ijj69vWLefuUtoRbubnteLRgEN1h69+gtTAmB4wqQ3QqequH6Lh3KCp7NNy/G8AFXOJn394q6ausNUknLmBWvB5q6AE2tDqYD4hI=
