language: ruby
rvm:
- 2.2.3
install:
- bundle install --retry=3
script:
- bundle exec rubocop
- bundle exec rspec
notifications:
  slack:
    secure: J0D3Guhqn7FRRjJfow4bCmoOn8DCdDRxhxEUkSDOfOzgMt9cn+FfX1FT38cBOuHOn7hLUryjjiHU5zsSQMwiNo7tOj7IW88IiUP4pu6J8dGMjnUP9mO7PFAUIGMHIFm7ANO1jDSMxq+Iwv7HZz35h5Ok1thwb2Qfee4/qg2sJ2eDWbHlfrCjCylUVKUTjvX5RaHY31cVW5t/VrenMP2r2k0A4mzYDdFWk/BSpWpcw2ahjnyUGc1g1MkDOf+NxW+gaSIxDXH1wYFo83smASqHpEdyumlUzBCYpqBVl7pJSRE5tmi+lRg1lqXhYzsS65rB67ysxCpx7zzvOHT62IIieURUgx4jmLqJB9NQ4JOT885uUU/pTtt7pEiKrgTDwv8j8wUMZU3q0xtmfDZ/FSAqAy4UGiIWPREWjMhzuFv6GkuMHYPagtt2POJ/UeioF2XPT9Th9otdv0ys07YDAW1Ktk+TLTXqhjB96GS2NU8DzW4z2Hz20hwSqT3IiOzceLrCzWIuFQeqdY5Dusxeoe6G4Zn6UxRByRdGn0zlRrXxgTD7dY3ym63Bij6TAf6gYxpRM7+oYMN0r023z7NxffugBBz/wPOk8tD3TN37g62FVTVxXt7tIkdoofH2Ko1d2zN3rssrrJ4rJLry5OvYAUc8WL93hQf4VVZwr4PN3YkT1c0=
    on_success: change
  flowdock:
    secure: LuhbnBcKmSr1FBtVV2BGxi2HE5mdD0hc7km0k+0o8S2Sh1H9VwfOmSN7/CPXbeXJM+rdhYDOSmr6Smih+jhNy4tvjxltSawTchriJQbBWbIuwWZav6Py8yJoyMBR9jTbFCV3ZMSRT0z/s2IA9/Uh6/txx6f3FHmn0qXRF4TX98Fe45w/CZiQY7GPzb/rYEB4zmuHuTJvL5iEuV2Mq2zz01sHzBhmSmdCy2tIxAZ+XHjJ0MYasLAhBNAJ1o5GsRLuHCNAoiztf1bsGnoqmCsIl+w4fwpQr46lriLpP5IOM8fynmu/lhI3Wz01MMwM9OlKyV9Syt7iz//qk9QSAqqvm+4Y5Ixlf6TxnwhEMvrVv6qHaOyHW1yrrNcRv7AiuXHXAwix5WaiZmEaJAeOLBBTpSEzi2kVRr5piF9dU/xbFOupMrgyn8QOhsPbwoVwR0YSK9OrlTxPwLCzhSJx1O2M/0WbxY/fOxopSAl3j/MZ+5tGVQwzzeuHEev3iSKIODwXGloBmZ+AnEuZee/6qyPzoW62x1FKhEQhyqDTcUqeuf1kST83mGAEQRtUb+/8npYVdJ6qfB3Ijj69vWLefuUtoRbubnteLRgEN1h69+gtTAmB4wqQ3QqequH6Lh3KCp7NNy/G8AFXOJn394q6ausNUknLmBWvB5q6AE2tDqYD4hI=
    on_success: change
