language: ruby
rvm:
- 2.2.3
install:
- bundle install --retry=3
script:
- bundle exec rubocop
- bundle exec rspec
notifications:
  slack:
    rooms:
      - sawyereffect:bdqwRIHvT8URlzmZVs1kYsBq#notifications
    on_success: change
