---
log:
  file: /dev/null
  date_format: '%Y-%m-%d %H:%M:%S'
  level: DEBUG
input:
  csv:
    file: data_examples/products.csv
output:
  xml:
    catalog:
      file: data_examples/catalog.xml
      encoding: UTF-8
      id: nagual-catalog
      xmlns: http://www.demandware.com/xml/impex/catalog/2006-10-31
      images:
        path: /
        alt: ${productname}
        title: ${productname}
      view_types:
        - large
        - medium
        - small
        - swatch
      variation_attributes:
        - color
    product:
      lang: x-default
      image: 'images/%{id}_%{name}.png'
      variant: '%{name}_%{modifier}'
  error_report:
    file: data_examples/error_report
contract:
  product:
    required:
      - product_id
    fields:
      product_id: string.100
      ean: string.256
      upc: string.256
      unit: string.256
      min_order_quantity: decimal
      step_quantity: decimal
      display_name: string
      short_description: string
      long_description: string
      online_flag: boolean
      online_from: datetime
      online_to: datetime
      available_flag: boolean
      searchable_flag: boolean
      searchable_if_unavailable_flag: boolean
      template: string.256
      tax_class_id: string.256
      brand: string.256
      manufacturer_name: string.256
      manufacturer_sku: string.256
      search_placement: int
      search_rank: int
      sitemap_included_flag: boolean
      sitemap_changefrequency: frequency
      sitemap_priority: priority
      page_title: string
      page_description: string
      page_keywords: string
      page_url: string
mapping:
  product:
    columns:
      id: product_id
      ean: ean
      upc: upc
      unit: unit
      step: step_quantity
      name: display_name
      description: short_description
      online: online_flag
      from: online_from
      to: online_to
      available?: available_flag
      searchable?: searchable_flag
      'searchable if unavailable?': searchable_if_unavailable_flag
      template: template
      'tax class id': tax_class_id
      brand: brand
      manufacturer: manufacturer_name
      SKU: manufacturer_sku
      placement: search_placement
      rank: search_rank
      sitemap?: sitemap_included_flag
      'sitemap change frequency': sitemap_changefrequency
      'sitemap priority': sitemap_priority
      'page title': page_title
      'page description': page_description
      'page keywords': page_keywords
      'page url': page_url
      'organization': organization
    variations:
      - color
    images: images
decoration:
  product:
    values:
      min_order_quantity: 10
