---
log:
  file: /dev/null
  date_format: '%Y-%m-%d %H:%M:%S'
  level: DEBUG
input:
  csv:
    file: data_examples/products.csv
output:
  xml:
    catalog:
      file: data_examples/catalog.xml
      encoding: UTF-8
      id: nagual-catalog
      xmlns: http://www.demandware.com/xml/impex/catalog/2006-10-31
      images:
        path: /
        alt: ${productname}
        title: ${productname}
      view_types:
        - large
        - medium
        - small
        - swatch
      variation_attributes:
        - color
    product:
      lang: x-default
      image: 'images/%{id}_%{name}.png'
      variant: '%{name}_%{modifier}'
  error_report:
    file: data_examples/error_report
contract:
  product:
    required:
      - product_id
    fields:
      product_id: string.100
      ean: string.256
      upc: string.256
      unit: string.256
      min_order_quantity: decimal
      step_quantity: decimal
      display_name: string
      short_description: string
      long_description: string
      online_flag: boolean
      online_from: datetime
      online_to: datetime
      available_flag: boolean
      searchable_flag: boolean
      searchable_if_unavailable_flag: boolean
      template: string.256
      tax_class_id: string.256
      brand: string.256
      manufacturer_name: string.256
      manufacturer_sku: string.256
      search_placement: int
      search_rank: int
      sitemap_included_flag: boolean
      sitemap_changefrequency: frequency
      sitemap_priority: priority
      page_title: string
      page_description: string
      page_keywords: string
      page_url: string
mapping:
  product:
    mutations:
    - key: id
      to: product_id
      name: none
    - key: ean
      to: ean
      name: none
    - key: upc
      to: upc
      name: none
    - key: unit
      to: unit
      name: none
    - key: step
      to: step_quantity
      name: none
    - key: name
      to: display_name
      name: none
    - key: description
      to: short_description
      name: none
    - key: from
      to: online_from
      name: none
    - key: to
      to: online_to
      name: none
    - key: searchable?
      to: searchable_flag
      name: none
    - key: 'searchable if unavailable?'
      to: searchable_if_unavailable_flag
      name: none
    - key: template
      to: template
      name: none
    - key: 'tax class id'
      to: tax_class_id
      name: none
    - key: brand
      to: brand
      name: none
    - key: manufacturer
      to: manufacturer_name
      name: none
    - key: SKU
      to: manufacturer_sku
      name: none
    - key: placement
      to: search_placement
      name: none
    - key: rank
      to: search_rank
      name: none
    - key: sitemap?
      to: sitemap_included_flag
      name: none
    - key: 'sitemap change frequency'
      to: sitemap_changefrequency
      name: none
    - key: 'sitemap priority'
      to: sitemap_priority
      name: none
    - key: 'page title'
      to: page_title
      name: none
    - key: 'page keywords'
      to: page_keywords
      name: none
    - key: 'organization'
      to: organization
      name: none
    - key: status
      to: online_flag
      name: convert
      params:
        default: 'false'
        values:
          online: 'true'
    variations:
      - color
    images: images
decoration:
  product:
    fixed:
      min_order_quantity: 10
      available_flag: 'true'
    copy:
      - key: short_description
        to: page_description
    merge:
      - keys:
          - product_id
          - organization
        pattern: 'http://host/%{organization}/%{product_id}'
        to: page_url
