---
output_file: data/output.xml
catalog:
  attributes:
    xmls: 'http://www.demandware.com/xml/impex/catalog/2006-10-31'
products:
  file: data/products.csv
  attribute_keys:
    - :product-id
images:
  file: data/images.csv
  attribute_keys:
    - :path
image_groups:
  file: data/image_groups.csv
  attribute_keys:
    - :view-type
    - :variation-value
page_attributes:
  file: data/page_attributes.csv
  attribute_keys:
    -
