---
output_file: data/output.xml
catalog:
  attributes:
    xmls: 'http://www.demandware.com/xml/impex/catalog/2006-10-31'
tests:
  file: data_examples/products.csv
  attribute_keys:
    -
products:
  file: data/products.csv
  attribute_keys:
    - :product-id
images:
  file: data/images.csv
  attribute_keys:
    - :path
image_groups:
  file: data/image_groups.csv
  attribute_keys:
    - :view-type
    - :variation-value
page_attributes:
  file: data/page_attributes.csv
  attribute_keys:
    -
bundled_products:
  file: data/bundled_products.csv
  attribute_keys:
    - :product-id
product_links:
  file: data/product_links.csv
  attribute_keys:
    - :product-id
    - :type
product_set_products:
  file: data/product_set_products.csv
  attribute_keys:
    - :product-id
options:
  file: data/options.csv
  attribute_keys:
    - :mode
    - :option-id
option_values:
  file: data/option_values.csv
  attribute_keys:
    - :value-id
    - :default
option_value_prices:
  file: data/option_value_prices.csv
  attribute_keys:
    - :currency

