---
input_file: data/products.csv
input_test_file: data_examples/products.csv
output_file: data/catalog.xml
catalog_xsd: schema/catalog.xsd

catalog:
  attributes:
    xmlns: http://www.demandware.com/xml/impex/catalog/2006-10-31
    catalog-id: nagual-catalog
product:
  attribute_keys:
    - :product-id
    - :mode
  element_keys:
    - ean
    - upc
    - unit
    - min-order-quantity
    - step-quantity
    - display-name
    - short-description
    - long-description
    - online-flag
    - online-from
    - online-to
    - searchable-flag
    - searchable-if-unavailable-flag
    - images
    - template
    - tax-class-id
    - brand
    - manufacturer-name
    - manufacturer-sku
    - search-placement
    - search-rank
    - sitemap-included-flag
    - sitemap-changefrequency
    - sitemap-priority
header:
  :elements:
    - image-settings:
      - :elements:
        - internal-location:
          - :elements: [{}]
            :attributes:
              base-path: '/images'
          view-types:
          - :elements:
            - view-type: default
            :attributes: {}
          alt-pattern: ${productname}
          title-pattern: ${productname}
        :attributes: {}
  :attributes: {}
images:
  :elements:
    - image-group:
      - :elements:
        - image:
          - :elements: [{}]
            :attributes:
              path: 'default/'
        :attributes:
          view-type: default
  :attributes: {}
